### ISSUE TITLE
dhfudh

### ISSUE THREAD

**Issue by dundargoc** [neodundar/neovim#1]
### Neovim version (nvim -v)

df

### Vim (not Nvim) behaves the same?

fskdfjh

### Operating system/version

fdjh

### Terminal name/version

akjsdhf

### $TERM environment variable

aksjhdf

### Installation

asiudfh

### How to reproduce the issue

pssdiufh

### Expected behavior

pasudfh

### Actual behavior

apsidufh

**Comment by dundargoc** [comment]
I completely disagree

**Comment by dundargoc** [comment]
No, *you're* wrong.

**Comment by dundargoc** [comment]
no u

**Comment by dundargoc** [comment]
dafgkisadhfiusdh

**Comment by dundargoc** [comment]
shutupshutupshutupshutup

**Comment by dundargoc** [comment]
af

**Comment by dundargoc** [comment]
sp

**Comment by dundargoc** [comment]
WHY????????

**Comment by dundargoc** [comment]
BECAUSE!

**Comment by dundargoc** [comment]
funi

**Comment by ii14** [comment]
test

**Comment by dundargoc** [comment]
test as in testosterone?

**Comment by dundargoc** [comment]
toblerone?

**Comment by glepnir** [comment]
```
 \
 /                                 />
 \__+_____________________/\/\___/ /|
 ()______________________      / /|/\
             /0 0  ---- |----    /---\
            |0 o 0 ----|| - \ --|      \
             \0_0/____/ |    |  |\      \
                         \__/__/  |      \
Bang! Bang!                       |       \
                                  |         \
                                  |__________|
```

**Comment by dundargoc** [comment]
ow!

**Comment by dundargoc** [comment]
ow 2!

**Comment by dundargoc** [comment]
ow 3?

**Comment by glepnir** [comment]
ow 4 now

**Comment by dundargoc** [comment]
stale

**Comment by dundargoc** [comment]
test

**Comment by dundargoc** [comment]
dofij

**Comment by dundargoc** [comment]
fdjh

**Comment by dundargoc** [comment]
ye

**Comment by notdundargoc** [comment]
ratio

**Comment by dundargoc** [comment]
I'm here pls unstale

**Comment by dundargoc** [comment]
I'm here!!

**Comment by dundargoc** [comment]
noice

**Comment by seandewar** [comment]
🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥
🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥
🟥🟥🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟥🟥
🟥🟥🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟥🟥
🟥🟥🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟥🟥
🟥🟥🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟥🟥
🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥
🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥
🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥
🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥
🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥
🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥
🟥🟥🟥🟥🟥🟥 ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎🟥🟥🟥🟥🟥🟥
🟥🟥🟥🟥🟥🟥 ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ 🟥🟥🟥🟥🟥🟥

**Comment by dundargoc** [comment]
sus
