### ISSUE TITLE
neovim is broken

### ISSUE THREAD

**Issue by seandewar** [neodundar/neovim#795]
### Neovim version (nvim -v)

1.0

### Vim (not Nvim) behaves the same?

fdsfds

### Operating system/version

dsfdfdsfds

### Terminal name/version

fdsfdfsfdsfs

### $TERM environment variable

dfdsfsdf

### Installation

fdfdsfdsfdfs

### How to reproduce the issue

fsdfdfds

### Expected behavior

it work

### Actual behavior

it don't work :(

**Comment by dundargoc** [comment]
ratio

**Comment by dundargoc** [comment]
yo
